name: school_management_system
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2  # More flexible & future-proof

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # Networking & API
  dio: ^5.9.0            # update when stable
  http: ^1.2.2

  # State & DI
  provider: ^6.1.2
  get_it: ^7.7.0

  # Storage & prefs
  shared_preferences: ^2.3.0
  get_storage: ^2.1.1

  # UI & animations
  lottie: ^3.1.2
  animate_do: ^3.3.4
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.1
  flutter_animated_dialog: ^2.0.1

  # Images & files
  image_picker: ^1.1.2
  file_picker: ^8.1.0
  cached_network_image: ^3.4.0
  image_gallery_saver: ^2.0.3
  screenshot: ^3.0.0
  image: ^4.0.17

  # Permissions & connectivity
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5

  # Persian & date
  shamsi_date: ^1.0.2
  persian_datetime_picker: ^3.2.0
  intl: ^0.20.2

  # Others
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  logger: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1  # update to latest patch

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Book_loading.json
    - assets/animations/STUDENT.json
    - assets/images/app_logo.png

  # fonts: (add later if needed)
  #   - family: Vazir
  #     fonts:
  #       - asset: fonts/Vazir-Regular.ttf
